### ISSUE TITLE
graspit-simulator problem

### ISSUE THREAD

**Issue by emigmo** [JenniferBuehler/graspit-pkgs#22]
When following your wiki to build the 'graspit-pkgs' package,
Where can I find my graspit-simulator or how can set the $GRASPIT  environment variable ?

**Comment by JenniferBuehler** [comment]
I guess you are refering to [this page](https://github.com/JenniferBuehler/graspit-pkgs/wiki/Setting-up-GraspIt)?

I can't remember off the top of my head where it is put and I don't have it installed on the computer I'm in front of right now.. but it should be somewhere in your catkin workspace devel directory. Maybe do a ``locate dlr_flask.xml`` to see where one of the graspit sample models got put in?

**Comment by emigmo** [comment]
Yes, Find It. Thank you
