### ISSUE TITLE
graspit! I can not see the screen.

### ISSUE THREAD

**Issue by ambl2357** [JenniferBuehler/graspit-pkgs#33]
![default](https://user-images.githubusercontent.com/28953478/38367127-c8732744-391c-11e8-8e7a-a821fcb49dd2.JPG)

I have run the 'graspit_simulator'

but  UI is blank.

QPixmap::fromMimeSource: Cannot find pixmap "filenew.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "fileopen.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "filesave.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "play.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "prevMark.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "mark.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "collide.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "translateTool.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "rotateTool.xpm" in the mime source factory
QPixmap::fromMimeSource: Cannot find pixmap "selectTool.xpm" in the mime source factory

and i failed to open world.xml

**Comment by ambl2357** [comment]
my misstake sorry

**Comment by xyaoab** [comment]
Hey, can I know how you solved it?

**Comment by JenniferBuehler** [comment]
I will also have a look if I can reproduce this, but won't get the time before a while.

Meanwhile you can also just use the graspit simulator from the original repository to open the files.

**Comment by m-asahi** [comment]
As a quick fix, copy all the image files in catkin_ws/build/graspit-pkgs/grasp_planning_graspit/graspit_external/repo/graspit/src/images to catkin_ws and always rosrun from catkin_ws.

At first viewing, grasp_planning_graspit/graspit_external/repo/graspit/CMakeList.txt under the build folder generates grasp_planning_graspit/graspit_external/graspit-build/qt_image_collection.cpp, but there seems to be no code accessing the staticImages instance defined here.

**Comment by JenniferBuehler** [comment]
This is not relevant any more. The source has just been changed, now graspit needs to be installed separetely from the original respository, so you will be using the original ``graspit_simulator``.

Please update my packages you are using and refer to the updated wiki for installation instructions (not much has changed, you will only need to install graspit separately, then re-build your catkin workspace, and the graspit simulator is then just started with ``graspit_simulator``).
