### ISSUE TITLE
How to save a screenshot together with iv and xml files

### ISSUE THREAD

**Issue by mkokic** [JenniferBuehler/graspit-pkgs#35]
Hi! I've managed to run 
**roslaunch grasp_planning_graspit_ros graspit_planner_jaco_example.launch \
    results_output_directory:=<your-results-directory>**
and save the inventor and world files. However, I would also like to also save a "screenshot" of the scene - similar to Save Image when running  _graspit_interface_. I've tried adding a function to _GraspitSceneManager_ that does something like:
**core->getIVmgr()->saveImage(filename.c_str());**
The code can compile but it breaks when I try to execute it. Do you have any idea how to do this? Thanks a lot!

**Comment by JenniferBuehler** [comment]
Hi, this should be possible, can you be more specific about how it "breaks", is it a segmentation fault at the call of `saveImage`?

**Comment by JenniferBuehler** [comment]
Since I haven't heard back, I presume you have fixed this and will close the issue. Please re-open if you keep having problems.
