### ISSUE TITLE
linking in the wiki got some typo

### ISSUE THREAD

**Issue by artemiialessandrini** [JenniferBuehler/graspit-pkgs#46]
[urdf2graspit wiki](https://github.com/JenniferBuehler/graspit-pkgs/wiki/Conversion-with-urdf2graspit)
```
cd $GRASPIT/models/robots
ls -s <path-to-YOUR_ROBOT-folder>
```
Suppose, it should be `ln -s `:)

There's another one right after this.

**Comment by JenniferBuehler** [comment]
Yes, thanks :)
