### ISSUE TITLE
how to obtain a urdf file?

### ISSUE THREAD

**Issue by majiqiang** [JenniferBuehler/graspit-pkgs#49]
now i just have 3d mesh file in SolidWorks, i want to obtain iv and xml file in graspit. so will I experience these conversion 3d mesh->urdf->graspit? thank you!

**Comment by mattcorsaro1** [comment]
[sw_urdf_exporter](http://wiki.ros.org/sw_urdf_exporter)
https://github.com/graspit-simulator/graspit/issues/155#issuecomment-495028814

**Comment by JenniferBuehler** [comment]
I'm closing this because there was no more movement here. Please reopen if it's not resolved.
