### ISSUE TITLE
error: urdf to robot.xml

### ISSUE THREAD

**Issue by majiqiang** [JenniferBuehler/graspit-pkgs#51]
why show this error
![1561122761(1)](https://user-images.githubusercontent.com/37575460/59924888-5c264680-9469-11e9-989d-3e1fc29d75f8.jpg)
load robot.xml failed.
this is my urdf model and robot.xml.
please help me!
[robots.zip](https://github.com/JenniferBuehler/graspit-pkgs/files/3314597/robots.zip)
[today615.zip](https://github.com/JenniferBuehler/graspit-pkgs/files/3314600/today615.zip)

**Comment by JenniferBuehler** [comment]
Sorry I don't know what this says. It may be a segmentation fault? Which robot are you using?

**Comment by majiqiang** [comment]
> Sorry I don't know what this says. It may be a segmentation fault? Which robot are you using?

**Comment by majiqiang** [comment]
> Sorry I don't know what this says. It may be a segmentation fault? Which robot are you using?

Thanks for your reply, the robot I'm using is usual, this is its picture and 3D mesh file. I use the plugin [sw_urdf_exporter](http://wiki.ros.org/sw_urdf_exporter) to get urdf file. Could you help me check if the urdf file is right?
[myurdf.tar.gz](https://github.com/JenniferBuehler/graspit-pkgs/files/3341953/myurdf.tar.gz)
![dh_hand](https://user-images.githubusercontent.com/37575460/60385326-8eafef00-9aba-11e9-9a50-2ff3ce486316.png)

**Comment by JenniferBuehler** [comment]
I think the URDF is fine as long as you can view it correctly in RVIZ. I guess you are then using urdf2graspit to convert to graspit format?
If you could also translate what the error message says that would be helpful. I'm suspecting segmentation fault. I presume you are using the newest version of this repository and graspit?

**Comment by majiqiang** [comment]
> I think the URDF is fine as long as you can view it correctly in RVIZ. I guess you are then using urdf2graspit to convert to graspit format?
> If you could also translate what the error message says that would be helpful. I'm suspecting segmentation fault. I presume you are using the newest version of this repository and graspit?

Yes，I can view it in rviz, but it's a little wrong as this picture. I don't know how to form a closed loop chain in urdf. Maybe that plugin don't support the feature, I don't know.
I am using the newest version of this repository [urdf2graspit](https://github.com/JenniferBuehler/graspit-pkgs/wiki/Conversion-with-urdf2graspit)
![rviz](https://user-images.githubusercontent.com/37575460/60407336-f5cdc080-9bec-11e9-8b56-502689bc4920.jpg)

**Comment by JenniferBuehler** [comment]
Judging from your other issue, you managed to get rid of the segmentation fault?
