### ISSUE TITLE
i can't diplay 5 finger's shadow hand model on graspit_simulator.

### ISSUE THREAD

**Issue by ghost** [JenniferBuehler/graspit-pkgs#54]
Nice to meet you.
I challenged to display a five-finger shadow hand model on grasspit_simulator.
I read the getting started of "Step 1. Choose your robot model" on the following page.
https://github.com/JenniferBuehler/graspit-pkgs/wiki/Getting-started

However, an error message was displayed and could not be resolved.
Can you tell me how to deal with it?
The robot model file was attached into this issue page.

initial@adonis:~/automnp_ws/src/automnp_simulator/automnp_mujoco/graspit$ ./build/graspit_simulator -w shadowhand_motor_world
Creating base...

Setting up 22 degrees of freedom...
Creating 5 kinematic chains (fingers)...
Chain 0:   Creating joints
   Joint 0
   Joint 1
   Joint 2
   Joint 3
  Creating links
   Link 0
   Link 1
   Link 2
   Link 3
  Creating dynamic joints
Chain 1:   Creating joints
   Joint 0
   Joint 1
   Joint 2
   Joint 3
   Joint 4
  Creating links
   Link 0
   Link 1
   Link 2
Coin read error: Couldn't read value for field "translation" of Transform
	Occurred at line   9 in /home/initial/automnp_ws/src/automnp_simulator/automnp_mujoco/graspit/models/robots/shadowhand_motor/iv/rh_lfproximal.iv
A problem occurred while reading Inventor file/home/initial/automnp_ws/src/automnp_simulator/automnp_mujoco/graspit/models/robots/shadowhand_motor/iv/rh_lfproximal.iv
Failed to open geometry file: /home/initial/automnp_ws/src/automnp_simulator/automnp_mujoco/graspit/models/robots/shadowhand_motor/iv/rh_lfproximal.iv
Failed to load file for link 2
Failed to read chain 1
Failed to load robot from file
Deleting Hand: 
Deleting grasp
Deleted robot: 
Could not open /home/initial/automnp_ws/src/automnp_simulator/automnp_mujoco/graspit/models/robots/shadowhand_motor/shadowhand_motor.xml
Failed to Parse args.

**Comment by ghost** [comment]
This is the robot model which is composed by shadow hand and ur10 arm.
[shadowhand_with_ur10.zip](https://github.com/JenniferBuehler/graspit-pkgs/files/3696076/shadowhand_with_ur10.zip)

This is output folder made by urdf2graspit.launch(including urdf2graspit_node) and graspit_contacts_generator.launch 
[output.zip](https://github.com/JenniferBuehler/graspit-pkgs/files/3696075/output.zip)

This urdf2graspit_node could output following file.
[urdf2graspit.txt](https://github.com/JenniferBuehler/graspit-pkgs/files/3696095/urdf2graspit.txt)

In output\models\robots\shadowhand_motor\iv folder, rh_lfdistal.iv, rh_lfproximal.iv and rh_lfmiddle.iv have strange output within Transform variable which have elements of "nan".

When I compared the both axes of URDF(left in figure) and DH(right), the axes were not same.
Around the root of little finger, axes rotated a bit to different direction.
![URDFaxes_and_DHaxes](https://user-images.githubusercontent.com/7998122/66295069-748d7480-e925-11e9-9463-0fc3d5249615.png)

I could setup contact points without any trouble but the final output (shadowhand_motor_world.xml) of step1 was not displayed on graspit simulator.
![contact_points](https://user-images.githubusercontent.com/7998122/66295237-d057fd80-e925-11e9-9217-618868c35688.png)

**Comment by JenniferBuehler** [comment]
Thanks for reporting this! I will try and look at it this weekend.

**Comment by ghost** [comment]
I use an official shadow hand URDF model ( included in shadowhand_with_ur10.zip) which was provided by shadow company. The URDF is used on GAZEBO or MOVEIT without any problem. When I use the URDF file, the first step of urdf2graspit seems to fail to convert URDF to Graspit data format around the little finger. and then the latter step can not use the transform information. The converted XML has -NAN but not a specific value on the little finger transformation. In the URDF file, the dismal, middle and proximal link and joint information for little finger have completely same parameters as other fingers meaning first, middle and ring finger.  The joint "rh_LFJ5" which is root joint for little finger only has a bit twisted axis parameters comparing with other joint. As an example, I show a part of information of my URDF file.
   
>    <joint name="rh_LFJ5" type="revolute"
>       <parent link="rh_palm"/
>       <child link="rh_lfmetacarpal"/
>       <origin rpy="0 0 0" xyz="-0.033 0 0.02071"/
>       <axis xyz="0.573576436 0 0.819152044"/
>       <limit effort="1.0" lower="0" upper="0.785398163397" velocity="2.0"/
>       <dynamics damping="0.1"/
>   </joint

I removed ">" from the script due to an editing error. I hope this comment will help this problem solves.

**Comment by JenniferBuehler** [comment]
Hello, I was just going to test it, but unfortunately the meshes don't come in your .zip file. I cannot find the official repository for that same file. Could you please provide the full directory `shadow_launch`?

**Comment by ghost** [comment]
I appreciate your reply. I pushed my packages with graspit modules on my repository. How to reproduce my error is written in README.md.  Link is below.
https://github.com/masa1120/graspit_sr_ur

**Comment by JenniferBuehler** [comment]
Sorry it took me so long, I simply didn't have time in the past couple of weeks :/
I looked into it and I think I fixed it. At least there are no nan values any more, but I'm having separate issues with the graspit simulator at the moment (I can't load any worlds), so I couldn't open the converted files to check if it looks like it makes sense. Would you mind checking that? I'm not sure when I'll sort out the graspit simulator issue...

**Comment by JenniferBuehler** [comment]
Thanks btw for providing your packages on github, and the description in the README. This made testing a lot easier :)

**Comment by masa1120** [comment]
Hi, I appreciate your reply. Let me understand your code deeply to modify your code in the future if it is needed. From first, I started to understand your codes by JACO robot model. when display JACO URDF on RVIZ and your viewer, the direction of axis never match. why do you rotate an axis intentionally within your urdf_viewer.launch?

![Screenshot from 2019-10-29 23-42-38](https://user-images.githubusercontent.com/7998122/67828922-8c1cdf00-fb18-11e9-961b-9a9c08955283.png)

Your JACO only has three fingers and each finger only has one revolute joint. In the JACO model, the "contact_generator_node" never use DHParam::toDenavitHartenberg function to calculate DH-parameters. When I checked, your code skipped to call DHParam::toDenavitHartenberg function within Urdf2GraspIt::getDHParams function. If one finger only has one joint, the joint equals the root joint for each finger. The DH-parameters of the finger root joint are inserted all zero at the end of Urdf2GraspIt::getDHParams function. On case which each finger has multiple joints, I can not check if your code run well.

**Comment by masa1120** [comment]
By using contacts_generator_node, can you display following robot model? that is shadow hand model without visual data. 

[shadowhand_with_ur10_left_simple2_without_visual.urdf.zip](https://github.com/JenniferBuehler/graspit-pkgs/files/3786984/shadowhand_with_ur10_left_simple2_without_visual.urdf.zip)

When you input abobe data into your contacts_generator_node, according to needs, please use following cpp. At the begin of main function, I wrote path scripts. You can change path information on the "shadowhand_with_ur10_left_simple2_without_visual.urdf". 

[contacts_generator_node.cpp.zip](https://github.com/JenniferBuehler/graspit-pkgs/files/3786991/contacts_generator_node.cpp.zip)

When "displayDHAxes" is true and  false, if your viewer shows same axes orientations on all joints, it means that your code never has problem. But when I check, the result was like this. On the following picture, there are two robot models. Left model is the axes orientation when "displayDHAxes" is false. This means the left axes orientation shows the axes of URDF definition. Right model is the axes orientation when "displayDHAxes" is true. This means the right axes orientation shows the axes of DH definition. Is it natural to have the same axis orientation on both definition of URDF and DH? In the case of JACO model, if each finger had multiple joints, I could search what was cause. Please tell me how to debug to confirm what is correct result.

![Screenshot from 2019-10-30 13-55-53](https://user-images.githubusercontent.com/7998122/67830287-67773600-fb1d-11e9-86dc-a1b8dc36c2a9.png)

**Comment by masa1120** [comment]
URDF2GRASPIT can understand negative value and decimal value of axes tag in URDF definition? I changed all axes is positive int value from previous model. At present, what I want to ask you is way to solve the gap of axes orientation between URDF model and DH. But, I am wondering if the gap is problem or not...
