### ISSUE TITLE
Cannot generate RobotiQ 2F 85 with urdf2graspit pkg

### ISSUE THREAD

**Issue by ItzMeJP** [JenniferBuehler/graspit-pkgs#57]
Hi, 
I am trying to generate the same gripper with the same launch file described here https://github.com/JenniferBuehler/graspit-pkgs/issues/45 by @JenniferBuehler. When I insert the generated .xml in Graspit, I get the following:

![image](https://user-images.githubusercontent.com/13644313/69165614-c19a6400-0ae9-11ea-9f07-414321258997.png)

Could you help me? Maybe  @artemiialessandrini can attached your functional model of the gripper, please?

_Originally posted by @ItzMeJP in https://github.com/JenniferBuehler/graspit-pkgs/issues/45#issuecomment-555590932_

**Comment by JenniferBuehler** [comment]
Sorry this flew under the radar because in the email notification I got it looked like this was part of #45.
Since this is long ago, I will close this for now, referring to #45.
Please re-open if you still need help with this.
Sorry again for only seeing now that this is a separate issue.
