### ISSUE TITLE
Using urdf2graspit on Panda gripper - does not fully open or close in GraspIt!

### ISSUE THREAD

**Issue by karthikm-0** [JenniferBuehler/graspit-pkgs#58]
Hi Jennifer,

I attempted to integrate the Panda gripper to GraspIt using your urdf2graspit package. I am using the urdf as defined here: https://github.com/erdalpekel/franka_ros/tree/simulation/franka_description/robots

However, upon converting and opening the gripper in GraspIt it does not fully open or close. I believe this is the case because in Gazebo/RViz I am able to fully open and close the gripper. Would you have some idea as to why this may be happening? I've attached two screenshots and the converted GraspIt hand model if you would like to inspect.

Thanks!
![Open](https://user-images.githubusercontent.com/39807420/70821145-62f29e00-1da8-11ea-9cf1-c82d2ee85b36.png)
![Close](https://user-images.githubusercontent.com/39807420/70821146-62f29e00-1da8-11ea-90a2-39b21c346e8c.png)
[Panda_GraspIt.zip](https://github.com/JenniferBuehler/graspit-pkgs/files/3962076/Panda_GraspIt.zip)

**Comment by JenniferBuehler** [comment]
Hello, have you tried adjusting the eigengrasp values? The ones which are generated are just a rough example.

**Comment by karthikm-0** [comment]
Thank you Jennifer. I tried adjusting the values but unfortunately, it does not fully extend.

**Comment by chaiban** [comment]
Hello @karthikm-0 ,

Did you resolve the issue ? I am facing same issue.

Thank you !
