### ISSUE TITLE
how to open the gripper ? 

### ISSUE THREAD

**Issue by chaiban** [JenniferBuehler/graspit-pkgs#60]
I have a multi finger gripper but it is in completely closed position.

Are there any packages or tools that i could use to open the gripper and convert to graspit required format ?  

Any suggestions ? Thanks!

**Comment by JenniferBuehler** [comment]
If your robot is in URDF, you can use `urdf2graspit`, see [the wiki](https://github.com/JenniferBuehler/graspit-pkgs/wiki/Conversion-with-urdf2graspit). If it is not in URDF, then you need to convert it to URDF first.

If you have it in URDF, it is highly likely that the joints of the gripper are movable already.
