### ISSUE TITLE
How to save grasp?

### ISSUE THREAD

**Issue by hoangcuongbk80** [JenniferBuehler/graspit-pkgs#63]
Hi Jennifer,

I'd like to save grasp from EigeinGrasp Planners. Could you give me some suggestions?

I added:
```  
FILE *f = fopen("grasp.txt","w");
for (int i=0; i<mPlanner->getListSize(); i++) 
      mPlanner->getGrasp(i)->writeToFile(f);
fclose(f);
```
to egPlannerDlg.cpp and visualized Tx Ty Tz as point(x,y,z) as following:

![11](https://user-images.githubusercontent.com/10355081/86898279-c8bdc300-c108-11ea-9c36-1f7c2787dc8c.png)

I though the red points should be placed on object surface as touching points, but they do not. How to save touching points?

**Comment by JenniferBuehler** [comment]
Hi,

This question probably belongs to the graspit repo, I presume you weren't using my graspit-pkgs packages?
Generally, when you save a grasp, it would save the joint (denavit Hartenberg) parameters, and wrist pose, AFAIK. But it's been a while I dealt with the graspit core code in detail so I could remember this wrong...
I can take a look at the code and I'll be able to tell you exactly, but I won't have the time before next week unfortunately... Ping me if you haven't found the answer before then :)

**Comment by hoangcuongbk80** [comment]
Hi Jennifer,

Yes I should ask the question in the graspit repo, but they are not likely be active. Thank you for replying all my questions, really really helpful.
 
For saving grasps, I solved it. Just need modify egPlannerDlg.cpp a little bit.

I am having a new question. EigenGrasp Planner works for object and robot in the scene. But if I add an obstacle to the scene, the planner doesn't functional anymore. Is there any way to make the planner work with object with obstacles?

![22](https://user-images.githubusercontent.com/10355081/87288999-6267e480-c4fc-11ea-9e87-bff1c3a0ebf2.png)

**Comment by JenniferBuehler** [comment]
Yes I've used obstacles (see tutorials in wiki) so it should work. However if your object lies on the table with suitable grasp points badly reachable by the gripper, the planner will fail because it finds collisions with the table for the suitable grasps. Make sure you have enough contact points on the object. Maybe increasing number of iterations helps, or re-planning a few times

**Comment by hoangcuongbk80** [comment]
It works! Thank you!
