### ISSUE TITLE
Hello @karthikm-0 Panda Gripper not completely opening,

### ISSUE THREAD

**Issue by chaiban** [JenniferBuehler/graspit-pkgs#64]
Hello @karthikm-0 ,

Did you resolve the issue ? I am facing same issue.

Thank you !

_Originally posted by @chaiban in https://github.com/JenniferBuehler/graspit-pkgs/issues/58#issuecomment-669017836_

**Comment by JenniferBuehler** [comment]
Hello, thish was probably not meant to be a new issue. You already commented in #58.

**Comment by chaiban** [comment]
Sorry @JenniferBuehler  about that, but i did not get any reply from other person.
