### ISSUE TITLE
graspit_interface can't Import Robot on ROS-neotic, ubuntu 20.04

### ISSUE THREAD

**Issue by RyanJiao** [JenniferBuehler/graspit-pkgs#66]
Hi, I followed the installation as @DavidWatkins instructed in this issue: #62 . And I could suceessfully run the graspit_interface.launch. However, the gui will stop working when I click the File -> Import Robot button. 

The gui will color will get a little bit darker than before. Is this something wrong with the qt5? 
![stop_working](https://user-images.githubusercontent.com/56286149/222036987-36893fcf-7592-4610-9319-2266d06ab2c4.png)

**Comment by RyanJiao** [comment]
![stop_working](https://user-images.githubusercontent.com/56286149/222036872-45f9a045-66d2-43d6-a0b7-796ee17c2de9.png)

**Comment by k3rth1v5n** [comment]
I am too having the same issue

**Comment by JenniferBuehler** [comment]
This would be a question for the `graspit-simulator` repo. I'm not actively working with Graspit at the moment, so I'm not as knowledeable about the current tricks and caveats ;)
